# Generated by Django 5.0 on 2024-01-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_origen', models.GenericIPAddressField()),
                ('directorio_origen', models.CharField(max_length=255)),
                ('ip_destino', models.GenericIPAddressField()),
                ('directorio_destino', models.CharField(max_length=255)),
                ('periodicidad', models.CharField(max_length=255)),
                ('fecha_respaldo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena_bot', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('respaldo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.registrorespaldo')),
            ],
        ),
        migrations.AddField(
            model_name='registrorespaldo',
            name='servidor_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.servidor'),
        ),
    ]
