# Generated by Django 4.2.6 on 2024-01-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_origen', models.CharField(max_length=255)),
                ('directorio_origen', models.CharField(max_length=255)),
                ('servidor_destino', models.CharField(max_length=255)),
                ('directorio_destino', models.CharField(max_length=255)),
                ('periodicidad', models.CharField(max_length=255)),
                ('fecha_respaldo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena_bot', models.CharField(max_length=255)),
            ],
        ),
    ]
