# Generated by Django 4.2.6 on 2024-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_bots_registrorespaldo_reportes_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
